DE debian: 9.5-slim

LABEL  "com.github.actions.name" = "Hola mundo" 
LABEL  "com.github.actions.description" = "Escribir argumentos en la salida estándar" 
LABEL  "com.github.actions.icon" = "micrófono" 
LABEL  " com.github.actions.color " = " purple "

LABEL  "repository" = "http://github.com/octocat/hello-world" 
LABEL  "homepage" = "http://github.com/actions" 
LABEL  "serveer " = "Octocat <octocat@github.com> "

AÑADIR entrypoint.sh /entrypoint.sh
   ENTRYPOINT [ "/entrypoint.sh" ]
